sudo: false
language: node_js
node_js:
  - "10.0.0"
  - "11.0.0"
  - "12.0.0"
  - "13.0.0"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run coverage.report
  - npm run semantic-release
